# Generated by Django 5.2.15 on 2026-06-21 14:09

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='scroll_bg_opacity',
            field=models.DecimalField(decimal_places=2, default=0.2, help_text='Maximum opacity when a background is fully visible (0.0–1.0). For example, 0.4 = 40%.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Scroll background opacity'),
        ),
        migrations.CreateModel(
            name='WebPageScrollBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Background image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='scroll_backgrounds', to='website.webpage')),
            ],
            options={
                'verbose_name': 'scroll background image',
                'verbose_name_plural': 'scroll background images',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
