# Generated by Django 5.2.15 on 2026-06-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0012_clear_all_catalogindex_custom_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Optional image for this collection (catalog index and collection page).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Cover image'),
        ),
    ]
