# Generated by Django 5.2.15 on 2026-06-23 13:39

import modelcluster.fields
from django.db import migrations


def migrate_edition_fk_to_m2m(apps, schema_editor):
    EditionPage = apps.get_model("website", "EditionPage")
    for edition in EditionPage.objects.all():
        if edition.content_language_id:
            edition.content_languages.add(edition.content_language_id)
        if edition.content_script_id:
            edition.content_scripts.add(edition.content_script_id)


def migrate_edition_m2m_to_fk(apps, schema_editor):
    EditionPage = apps.get_model("website", "EditionPage")
    for edition in EditionPage.objects.all():
        language = edition.content_languages.order_by("pk").first()
        script = edition.content_scripts.order_by("pk").first()
        edition.content_language_id = language.pk if language else None
        edition.content_script_id = script.pk if script else None
        edition.save(update_fields=["content_language_id", "content_script_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0003_remove_edition_collection_and_more"),
        ("website", "0013_collectionpage_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="editionpage",
            name="content_languages",
            field=modelcluster.fields.ParentalManyToManyField(
                help_text="Language(s) of the source text (not the site UI locale).",
                related_name="edition_pages",
                to="snippets.contentlanguage",
                verbose_name="content languages",
            ),
        ),
        migrations.AddField(
            model_name="editionpage",
            name="content_scripts",
            field=modelcluster.fields.ParentalManyToManyField(
                help_text="Writing system(s) used in this edition.",
                related_name="edition_pages",
                to="snippets.contentscript",
                verbose_name="content scripts",
            ),
        ),
        migrations.RunPython(
            migrate_edition_fk_to_m2m,
            migrate_edition_m2m_to_fk,
        ),
        migrations.RemoveField(
            model_name="editionpage",
            name="content_language",
        ),
        migrations.RemoveField(
            model_name="editionpage",
            name="content_script",
        ),
    ]
