# Generated by Django 5.2.15 on 2026-06-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_sync_migrated_body_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionpage',
            name='isbn_number',
            field=models.CharField(blank=True, help_text='ISBN-10 or ISBN-13 (hyphens optional).', max_length=20, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='editionpage',
            name='place_of_publication',
            field=models.CharField(blank=True, help_text='City or locality of publication (เมืองที่พิมพ์).', max_length=255),
        ),
    ]
