# Generated by Django 5.2.15 on 2026-06-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_edition_place_of_publication_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumepage',
            name='isbn_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='volumepage',
            name='place_of_publication',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='editionpage',
            name='isbn_number',
            field=models.CharField(blank=True, help_text='Default ISBN-10 or ISBN-13 (hyphens optional). A volume may override it.', max_length=20, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='editionpage',
            name='place_of_publication',
            field=models.CharField(blank=True, help_text='Default place of publication; a volume may override it.', max_length=255),
        ),
    ]
