# Generated by Django 5.2.15 on 2026-06-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_volumepage_place_of_publication_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionpage',
            name='physical_volume_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of physical bound volumes when it differs from volume sets (e.g. 57 when some sets comprise more than one bound book). Leave blank when equal to volume set count.', null=True),
        ),
        migrations.AddField(
            model_name='editionpage',
            name='volume_set_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of logical volume sets in this edition as catalogued (e.g. 52 for an edition published in 52 numbered sets).', null=True),
        ),
    ]
