# Generated by Django 5.2.16 on 2026-07-17 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0004_country_on_collection"),
        ("website", "0026_remove_chinese_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionpage",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Country of this scripture collection (not place of publication). "
                    "e.g. Chaṭṭha Saṅgīti printed in Taiwan still belongs to Myanmar."
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="snippets.country",
                verbose_name="ประเทศ / Country",
            ),
        ),
    ]
