# Generated by Django 5.2.16 on 2026-09-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_volumepage_scan_folio_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpage',
            name='code',
            field=models.CharField(help_text='Stable identifier, not translated. Used in scan paths, citations, imports, and as the page slug (URL). Unique among siblings.', max_length=64),
        ),
        migrations.AlterField(
            model_name='editionpage',
            name='code',
            field=models.CharField(help_text='Stable identifier, not translated. Used in scan paths, citations, imports, and as the page slug (URL). Unique among siblings.', max_length=64),
        ),
        migrations.AlterField(
            model_name='editionpage',
            name='physical_volume_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of physical books when it differs from volume sets (e.g. 57 books for 52 numbered sets when some numbers are split). Leave blank when equal to volume set count.', null=True),
        ),
        migrations.AlterField(
            model_name='volumepage',
            name='code',
            field=models.CharField(help_text='Stable identifier, not translated. Used in scan paths, citations, imports, and as the page slug (URL). Unique among siblings.', max_length=64),
        ),
        migrations.AlterField(
            model_name='volumepage',
            name='isbn_number',
            field=models.CharField(blank=True, help_text='Override for this volume only; leave blank to use the edition default.', max_length=20, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='volumepage',
            name='place_of_publication',
            field=models.CharField(blank=True, help_text='Override for this volume only; leave blank to use the edition default.', max_length=255),
        ),
        migrations.AlterField(
            model_name='volumepage',
            name='print_number',
            field=models.CharField(blank=True, help_text='Override for this volume only; leave blank to use the edition default.', max_length=64),
        ),
        migrations.AlterField(
            model_name='volumepage',
            name='published_year',
            field=models.CharField(blank=True, help_text='Override for this volume only; leave blank to use the edition default.', max_length=64),
        ),
        migrations.AlterField(
            model_name='volumepage',
            name='publisher',
            field=models.CharField(blank=True, help_text='Override for this volume only; leave blank to use the edition default.', max_length=255),
        ),
    ]
