# Generated by Django 5.2.15 on 2026-06-22 09:28

import django.db.models.deletion
import modelcluster.fields
import snippets.models.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('siglum', models.CharField(blank=True, help_text='Short code such as TP, AK, TK, AN (not translated).', max_length=8)),
                ('slug', models.SlugField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='snippets.classification')),
            ],
            options={
                'verbose_name': 'classification',
                'verbose_name_plural': 'classifications',
                'ordering': ['sort_order', 'slug'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'content language',
                'verbose_name_plural': 'content languages',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
            bases=(snippets.models.base.VocabularyPanelsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='snippets.classification')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('content_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='snippets.contentlanguage', verbose_name='content language')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'ordering': ['sort_order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'content script',
                'verbose_name_plural': 'content scripts',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
            bases=(snippets.models.base.VocabularyPanelsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(blank=True, help_text='Short identifier such as CH or BJ.', max_length=32)),
                ('slug', models.SlugField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='snippets.collection')),
                ('content_language', models.ForeignKey(blank=True, help_text="Optional override of the collection's content language.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to='snippets.contentlanguage', verbose_name='content language')),
                ('content_script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='snippets.contentscript', verbose_name='content script')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'edition',
                'verbose_name_plural': 'editions',
                'ordering': ['sort_order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'segment kind',
                'verbose_name_plural': 'segment kinds',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
            bases=(snippets.models.base.VocabularyPanelsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'tradition',
                'verbose_name_plural': 'traditions',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
            bases=(snippets.models.base.VocabularyPanelsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='collection',
            name='tradition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='snippets.tradition'),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, help_text='Optional volume number when the collection uses one.', max_length=64)),
                ('code', models.CharField(blank=True, help_text='Optional internal or import code.', max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=128)),
                ('edition', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='snippets.edition')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'volume',
                'verbose_name_plural': 'volumes',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='classification',
            constraint=models.UniqueConstraint(fields=('locale', 'slug'), name='snippets_classification_unique_locale_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AddConstraint(
            model_name='contentlanguage',
            constraint=models.UniqueConstraint(fields=('locale', 'code'), name='snippets_contentlanguage_unique_locale_code'),
        ),
        migrations.AddConstraint(
            model_name='contentlanguage',
            constraint=models.UniqueConstraint(fields=('locale', 'slug'), name='snippets_contentlanguage_unique_locale_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='contentlanguage',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AddConstraint(
            model_name='contentscript',
            constraint=models.UniqueConstraint(fields=('locale', 'code'), name='snippets_contentscript_unique_locale_code'),
        ),
        migrations.AddConstraint(
            model_name='contentscript',
            constraint=models.UniqueConstraint(fields=('locale', 'slug'), name='snippets_contentscript_unique_locale_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='contentscript',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AddConstraint(
            model_name='edition',
            constraint=models.UniqueConstraint(fields=('locale', 'slug'), name='snippets_edition_unique_locale_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AddConstraint(
            model_name='segmentkind',
            constraint=models.UniqueConstraint(fields=('locale', 'code'), name='snippets_segmentkind_unique_locale_code'),
        ),
        migrations.AddConstraint(
            model_name='segmentkind',
            constraint=models.UniqueConstraint(fields=('locale', 'slug'), name='snippets_segmentkind_unique_locale_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='segmentkind',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AddConstraint(
            model_name='tradition',
            constraint=models.UniqueConstraint(fields=('locale', 'code'), name='snippets_tradition_unique_locale_code'),
        ),
        migrations.AddConstraint(
            model_name='tradition',
            constraint=models.UniqueConstraint(fields=('locale', 'slug'), name='snippets_tradition_unique_locale_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='tradition',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('locale', 'slug'), name='snippets_collection_unique_locale_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('translation_key', 'locale')},
        ),
    ]
