# Generated by Django 5.2.15 on 2026-06-23 06:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0002_content_languages_m2m"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edition",
            name="collection",
        ),
        migrations.AlterUniqueTogether(
            name="edition",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="edition",
            name="content_languages",
        ),
        migrations.RemoveField(
            model_name="edition",
            name="content_script",
        ),
        migrations.RemoveField(
            model_name="edition",
            name="locale",
        ),
        migrations.RemoveField(
            model_name="volume",
            name="edition",
        ),
        migrations.AlterUniqueTogether(
            name="volume",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="volume",
            name="locale",
        ),
        migrations.CreateModel(
            name="CanonicalSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable short code such as vin, sut, dn, mn. Building block of cref.",
                        max_length=32,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=64)),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pitaka", "Piṭaka"),
                            ("nikaya", "Nikāya"),
                            ("section", "Section"),
                        ],
                        help_text="Level of this node within the canonical tree.",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="snippets.canonicalsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "canonical section",
                "verbose_name_plural": "canonical sections",
                "ordering": ["sort_order", "code"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Collection",
        ),
        migrations.DeleteModel(
            name="Edition",
        ),
        migrations.DeleteModel(
            name="Volume",
        ),
        migrations.AddConstraint(
            model_name="canonicalsection",
            constraint=models.UniqueConstraint(
                fields=("locale", "code"),
                name="snippets_canonicalsection_unique_locale_code",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="canonicalsection",
            unique_together={("translation_key", "locale")},
        ),
    ]
