# Generated by Django 5.2.16 on 2026-07-17 15:45

import django.db.models.deletion
import snippets.models.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_remove_edition_collection_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 country code (lowercase), e.g. th, mm, lk.', max_length=2)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('locale', 'code'), name='snippets_country_unique_locale_code'), models.UniqueConstraint(fields=('locale', 'slug'), name='snippets_country_unique_locale_slug')],
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(snippets.models.base.VocabularyPanelsMixin, models.Model),
        ),
    ]
