# Generated by Django 5.2.16 on 2026-07-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_country_on_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(help_text='Country code (lowercase), usually ISO 3166-1 alpha-2; e.g. th, mm, tib.', max_length=8),
        ),
    ]
