# Generated by Django 5.2.15 on 2026-06-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferenceAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            ("pts", "PTS"),
                            ("vri", "VRI / CST"),
                            ("thai_siam", "Thai (Siam Rath)"),
                            ("mahachula", "Mahāchulā"),
                            ("burmese_cs", "Burmese (Chaṭṭha Saṅgāyana)"),
                            ("sinhala_bjt", "Sinhala (BJT)"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Normalized legacy citation string (e.g. M.i.1).",
                        max_length=128,
                    ),
                ),
                ("cref", models.CharField(db_index=True, max_length=128)),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "reference alias",
                "verbose_name_plural": "reference aliases",
                "ordering": ["scheme", "value"],
            },
        ),
        migrations.CreateModel(
            name="ScanFolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        help_text="Physical order within the volume; used in path and nav."
                    ),
                ),
                (
                    "page_no",
                    models.CharField(
                        blank=True,
                        help_text="Printed page label (may be non-numeric: 'ก', 'iv', '42').",
                        max_length=32,
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True,
                        help_text="Full path override; blank = derive from the composite codes.",
                        max_length=512,
                    ),
                ),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("missing", "Missing"),
                            ("excluded", "Excluded"),
                            ("pending", "Pending"),
                        ],
                        default="present",
                        max_length=16,
                    ),
                ),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("iiif_id", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "scan folio",
                "verbose_name_plural": "scan folios",
                "ordering": ["volume", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(help_text="Reading order within the volume."),
                ),
                ("text", models.TextField()),
                (
                    "cref",
                    models.CharField(
                        db_index=True,
                        help_text="Edition-independent canonical reference (e.g. sut.mn.1.2).",
                        max_length=128,
                    ),
                ),
                ("cref_end", models.CharField(blank=True, max_length=128)),
                (
                    "structural_ref",
                    models.CharField(
                        blank=True,
                        help_text="Edition's own printed numbering (e.g. VRI paragraph).",
                        max_length=128,
                    ),
                ),
                (
                    "region",
                    models.JSONField(
                        blank=True,
                        help_text="Normalized bbox {x,y,w,h} (0–1). Required before publishing.",
                        null=True,
                    ),
                ),
                ("region_note", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "citation_key",
                    models.CharField(
                        help_text="Stable id for ?seg= links (unique within the volume).",
                        max_length=64,
                    ),
                ),
                ("source_note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "segment",
                "verbose_name_plural": "segments",
                "ordering": ["volume", "order"],
            },
        ),
        migrations.CreateModel(
            name="SegmentRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("cref", models.CharField(max_length=128)),
                ("region", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("change_note", models.CharField(blank=True, max_length=255)),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "segment revision",
                "verbose_name_plural": "segment revisions",
                "ordering": ["-created_at"],
            },
        ),
    ]
