# Generated by Django 5.2.15 on 2026-06-23 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("archive", "0001_initial"),
        ("snippets", "0003_remove_edition_collection_and_more"),
        ("website", "0007_catalogindexpage_collectionpage_editionpage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="referencealias",
            name="edition",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the scheme is edition-specific (e.g. a page number).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reference_aliases",
                to="website.editionpage",
            ),
        ),
        migrations.AddField(
            model_name="scanfolio",
            name="volume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scan_folios",
                to="website.volumepage",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="folio",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary scan folio this text appears on.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segments",
                to="archive.scanfolio",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="folio_end",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segments_end",
                to="archive.scanfolio",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segments",
                to="snippets.segmentkind",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="archive.segment",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="volume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segments",
                to="website.volumepage",
            ),
        ),
        migrations.AddField(
            model_name="segmentrevision",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="segment_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="segmentrevision",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="snippets.segmentkind",
            ),
        ),
        migrations.AddField(
            model_name="segmentrevision",
            name="segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="archive.segment",
            ),
        ),
        migrations.AddIndex(
            model_name="referencealias",
            index=models.Index(fields=["cref"], name="archive_ref_cref_5e800a_idx"),
        ),
        migrations.AddConstraint(
            model_name="referencealias",
            constraint=models.UniqueConstraint(
                fields=("scheme", "value", "edition"),
                name="archive_referencealias_unique_scheme_value_edition",
            ),
        ),
        migrations.AddIndex(
            model_name="scanfolio",
            index=models.Index(
                fields=["volume", "sequence"], name="archive_sca_volume__f7417c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scanfolio",
            constraint=models.UniqueConstraint(
                fields=("volume", "sequence"),
                name="archive_scanfolio_unique_volume_sequence",
            ),
        ),
        migrations.AddIndex(
            model_name="segment",
            index=models.Index(fields=["cref"], name="archive_seg_cref_503b25_idx"),
        ),
        migrations.AddIndex(
            model_name="segment",
            index=models.Index(
                fields=["volume", "order"], name="archive_seg_volume__c0778c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="segment",
            constraint=models.UniqueConstraint(
                fields=("volume", "citation_key"),
                name="archive_segment_unique_volume_citation_key",
            ),
        ),
        migrations.AddIndex(
            model_name="segmentrevision",
            index=models.Index(
                fields=["segment", "is_current"], name="archive_seg_segment_b966e3_idx"
            ),
        ),
    ]
