# Generated by Django 5.2.16 on 2026-09-03 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_initial'),
        ('snippets', '0005_country_code_tibet'),
        ('website', '0029_redesign_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencealias',
            name='edition',
        ),
        migrations.RemoveConstraint(
            model_name='segment',
            name='archive_segment_unique_volume_citation_key',
        ),
        migrations.RemoveIndex(
            model_name='segment',
            name='archive_seg_cref_503b25_idx',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='citation_key',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='cref',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='cref_end',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='folio_end',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='region_note',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='source_note',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='structural_ref',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='segmentrevision',
            name='cref',
        ),
        migrations.RemoveField(
            model_name='segmentrevision',
            name='text',
        ),
        migrations.AddField(
            model_name='segment',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Extract payload — multi-script text[], bats, notes, flags, …'),
        ),
        migrations.AddField(
            model_name='segment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segment',
            name='item',
            field=models.IntegerField(blank=True, db_index=True, help_text="Edition's printed item number (Tipiṭaka item). Null for headings/gāthā.", null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='plain_roman',
            field=models.TextField(blank=True, help_text='Flat Roman text derived from content for search/listing. Not source.'),
        ),
        migrations.AddField(
            model_name='segment',
            name='plain_thai',
            field=models.TextField(blank=True, help_text='Flat Thai text derived from content for search/listing. Not source.'),
        ),
        migrations.AddField(
            model_name='segment',
            name='section_no',
            field=models.IntegerField(blank=True, help_text='Outline number printed before a heading (e.g. `1` in `1. Pārājikakaṇḍa`).', null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='segmentrevision',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='segmentrevision',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentrevision',
            name='section_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentrevision',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='scanfolio',
            name='volume',
            field=models.ForeignKey(help_text='Default-locale volume page; other locales share these rows.', on_delete=django.db.models.deletion.PROTECT, related_name='scan_folios', to='website.volumepage'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='folio',
            field=models.ForeignKey(blank=True, help_text='Scan folio this unit sits on. May be empty on draft import.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='archive.scanfolio'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='kind',
            field=models.ForeignKey(help_text='Structural kind; code matches extract `segment_type` 1:1.', on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='snippets.segmentkind'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='order',
            field=models.IntegerField(help_text='Reading order within the volume; unique. Matches extract `order`.'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='region',
            field=models.JSONField(blank=True, help_text='Per-segment bbox {x,y,w,h} (0–1) on the folio image. Designed later.', null=True),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['item'], name='archive_seg_item_ffafac_idx'),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['kind'], name='archive_seg_kind_id_259678_idx'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('volume', 'order'), name='archive_segment_unique_volume_order'),
        ),
        migrations.DeleteModel(
            name='ReferenceAlias',
        ),
    ]
