# Generated by Django 5.2.16 on 2026-07-17 05:27

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunarImportantDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moon_phase', models.CharField(choices=[('01', 'ขึ้น'), ('02', 'แรม')], default='01', max_length=10, verbose_name='ข้างขึ้น-ข้างแรม')),
                ('day', models.CharField(choices=[('01', ' 1'), ('02', ' 2'), ('03', ' 3'), ('04', ' 4'), ('05', ' 5'), ('06', ' 6'), ('07', ' 7'), ('08', ' 8'), ('09', ' 9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=2, verbose_name='ค่ำ')),
                ('month', models.CharField(choices=[('01', '1'), ('02', '2'), ('03', '3'), ('04', '4'), ('05', '5'), ('06', '6'), ('07', '7'), ('08', '8'), ('09', '88'), ('10', '9'), ('11', '10'), ('12', '11'), ('13', '12')], max_length=2, verbose_name='เดือน')),
                ('moon_phase_adhikamasa', models.CharField(choices=[('01', 'ขึ้น'), ('02', 'แรม')], default='01', max_length=10, verbose_name='ข้างขึ้น-ข้างแรม (อธิกมาส)')),
                ('day_adhikamasa', models.CharField(choices=[('01', ' 1'), ('02', ' 2'), ('03', ' 3'), ('04', ' 4'), ('05', ' 5'), ('06', ' 6'), ('07', ' 7'), ('08', ' 8'), ('09', ' 9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=2, verbose_name='ค่ำ (อธิกมาส)')),
                ('month_adhikamasa', models.CharField(choices=[('01', '1'), ('02', '2'), ('03', '3'), ('04', '4'), ('05', '5'), ('06', '6'), ('07', '7'), ('08', '8'), ('09', '88'), ('10', '9'), ('11', '10'), ('12', '11'), ('13', '12')], max_length=2, verbose_name='เดือน (อธิกมาส)')),
            ],
            options={
                'verbose_name': 'วันสำคัญในปฏิทินจันทรคติ',
                'verbose_name_plural': 'วันสำคัญในปฏิทินจันทรคติ',
                'ordering': ['month', 'moon_phase', 'day'],
            },
        ),
        migrations.CreateModel(
            name='SolarImportantDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], verbose_name='วัน')),
                ('month', models.IntegerField(choices=[(1, 'มกราคม'), (2, 'กุมภาพันธ์'), (3, 'มีนาคม'), (4, 'เมษายน'), (5, 'พฤษภาคม'), (6, 'มิถุนายน'), (7, 'กรกฎาคม'), (8, 'สิงหาคม'), (9, 'กันยายน'), (10, 'ตุลาคม'), (11, 'พฤศจิกายน'), (12, 'ธันวาคม')], verbose_name='เดือน')),
            ],
            options={
                'verbose_name': 'วันสำคัญในปฏิทินสุริยคติ',
                'verbose_name_plural': 'วันสำคัญในปฏิทินสุริยคติ',
                'ordering': ['month', 'day'],
            },
        ),
        migrations.CreateModel(
            name='LunarImportantDayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อ')),
                ('is_buddhist_commemorative', models.BooleanField(default=True, verbose_name='วันสำคัญทางพุทธศาสนา')),
                ('article_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='บทความ')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='patidina.lunarimportantday', verbose_name='รายละเอียด')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolarImportantDayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อ')),
                ('article_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='บทความ')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='patidina.solarimportantday', verbose_name='รายละเอียด')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
